# Generated by Django 3.2.24 on 2024-03-31 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('book_date', models.DateField(null=True)),
                ('slot_time', models.CharField(max_length=30, null=True)),
                ('Status', models.CharField(max_length=300)),
                ('total', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Branch_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cosmeticproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=300)),
                ('Details', models.CharField(max_length=500)),
                ('Photo', models.FileField(upload_to='')),
                ('Uses', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('BRANCHID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch_table')),
                ('CATEGORY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category_table')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=20)),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facility_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facility', models.CharField(max_length=500)),
                ('Details', models.CharField(max_length=500)),
                ('Price', models.IntegerField()),
                ('Image', models.FileField(upload_to='')),
                ('Time', models.CharField(max_length=50)),
                ('BRANCHID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch_table')),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rentalbooking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(max_length=300)),
                ('Fromdate', models.DateTimeField(blank=True, null=True)),
                ('Todate', models.DateTimeField(blank=True, null=True)),
                ('Total', models.FloatField()),
                ('CUSTOMERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer_table')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='')),
                ('Basicpay', models.IntegerField()),
                ('Adharnumber', models.CharField(max_length=20)),
                ('BRANCHID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='Rentalproduct_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=300)),
                ('Description', models.CharField(max_length=300)),
                ('Image', models.FileField(upload_to='')),
                ('price', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
                ('BRANCHID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch_table')),
            ],
        ),
        migrations.CreateModel(
            name='Rentalbookingdetails_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=300)),
                ('RENTALBOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rentalbooking_table')),
                ('RENTALPRODUCTID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rentalproduct_table')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('date', models.DateField()),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.rentalbooking_table')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Percentage', models.IntegerField()),
                ('Fromdate', models.DateField()),
                ('Todate', models.DateField()),
                ('Image', models.FileField(upload_to='')),
                ('FACILITYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.facility_table')),
            ],
        ),
        migrations.CreateModel(
            name='Leaverequest_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.CharField(max_length=300)),
                ('Date', models.DateTimeField()),
                ('Numofdays', models.CharField(max_length=50)),
                ('Fromdate', models.DateField()),
                ('Status', models.CharField(max_length=200)),
                ('STAFFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.staff_table')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('Details', models.CharField(max_length=200)),
                ('Status', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('BRANCHID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacktobranch_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=300)),
                ('Rating', models.CharField(max_length=300)),
                ('Date', models.DateTimeField()),
                ('BRANCHID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.branch_table')),
                ('CUSTOMERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer_table')),
            ],
        ),
        migrations.CreateModel(
            name='Feedbacktoapp_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(max_length=300)),
                ('Rating', models.CharField(max_length=300)),
                ('Date', models.DateField()),
                ('CUSTOMERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer_table')),
            ],
        ),
        migrations.AddField(
            model_name='customer_table',
            name='LOGINID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.login_table'),
        ),
        migrations.CreateModel(
            name='Cosmeticstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(max_length=500)),
                ('Manufacturedate', models.DateField()),
                ('Expiringdate', models.DateField()),
                ('Price', models.IntegerField()),
                ('COSMETICID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cosmeticproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(max_length=500)),
                ('Date', models.DateTimeField()),
                ('Reply', models.CharField(max_length=500)),
                ('CUSTOMERID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer_table')),
            ],
        ),
        migrations.AddField(
            model_name='branch_table',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.login_table'),
        ),
        migrations.CreateModel(
            name='Bookingdetails_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('BOOKINGID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking_table')),
                ('FACILITYID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.facility_table')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.offer_table')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='CUSTOMERID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.customer_table'),
        ),
        migrations.CreateModel(
            name='Attendance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Attendance', models.CharField(max_length=400)),
                ('STAFFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.staff_table')),
            ],
        ),
        migrations.CreateModel(
            name='Assignwork_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Datetime', models.DateField()),
                ('Status', models.CharField(max_length=200)),
                ('BOOKINGID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.booking_table')),
                ('STAFFID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.staff_table')),
            ],
        ),
    ]
