# Generated by Django 3.2.24 on 2024-03-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='Date',
            field=models.DateField(),
        ),
    ]
