# Generated by Django 3.2.24 on 2024-03-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_complaint_table_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktobranch_table',
            name='Date',
            field=models.DateField(),
        ),
    ]
