# Generated by Django 3.2.24 on 2024-04-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_feedbacktobranch_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproduct_table',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
