# Generated by Django 3.2.24 on 2024-04-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rentalbookingdetails_table_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking_table',
            name='Fromdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalbooking_table',
            name='Todate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
