# Generated by Django 3.2.24 on 2024-04-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20240411_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalbooking_table',
            name='Date',
            field=models.DateField(),
        ),
    ]
