"""salon_management URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from App import views

urlpatterns = [
    path('ahome',views.adminhome,name='fst'),
    path('logincode',views.logincode,name='logincode'),
    path('delete_pet',views.delete_pet,name='delete_pet'),
    path('add_to_cart1',views.add_to_cart1,name='add_to_cart1'),
    path('admin_monthlyreports_post',views.admin_monthlyreports_post,name='admin_monthlyreports_post'),
    path('admin_monthlyreports',views.admin_monthlyreports,name='admin_monthlyreports'),
    path('login',views.login,name='login'),
    path('viewfeedbacksrch',views.viewfeedbacksrch,name='viewfeedbacksrch'),
    path('',views.mainhome,name='mainhome'),
    path('map',views.map,name='map'),
    path('addbranches',views.addbranches,name='addbranches'),
    path('managebranch',views.managebranch,name='managebranch'),
    path('view_returned_rental',views.view_returned_rental,name='view_returned_rental'),
    path('rental_returned_more/<id>',views.rental_returned_more,name='rental_returned_more'),
    path('addcateogory_post',views.addcateogory_post,name='addcateogory_post'),
    path('sendreply/<int:id>',views.sendreply,name='sendreply'),
    path('viewcomplaints',views.viewcomplaints,name='viewcomplaints'),
    path('viewcomplaintssrch',views.viewcomplaintssrch,name='viewcomplaintssrch'),
    path('rental_booking',views.rental_booking,name='rental_booking'),
    path('rental_booking_more/<id>',views.rental_booking_more,name='rental_booking_more'),
    path('rental_booking_return/<id>',views.rental_booking_return,name='rental_booking_return'),
    path('addreply',views.addreply,name='addreply'),
    path('viewcosmeticproduct',views.viewcosmeticproduct,name='viewcosmeticproduct'),
    path('viewfeedback',views.viewfeedback,name='viewfeedback'),
    path('viewfeedbacks',views.viewfeedbacks,name='viewfeedbacks'),
    path('viewproductrequest',views.viewproductrequest,name='viewproductrequest'),
    path('and_rental_booking_more',views.and_rental_booking_more,name='and_rental_booking_more'),
    path('addcosmetics',views.addcosmetics,name='addcosmetics'),
    path('viewcosmetics',views.viewcosmetics,name='viewcosmetics'),
    path('monthlyreports',views.monthlyreports,name='monthlyreports'),
    path('monthlyreports_post',views.monthlyreports_post,name='monthlyreports_post'),
    path('addinventory', views.addinventory,name='addinventory'),
    path('addinventory_post', views.addinventory_post,name='addinventory_post'),
    path('searchviewmanagefacility', views.searchviewmanagefacility,name='searchviewmanagefacility'),
    path('searchviewcosmetics', views.searchviewcosmetics,name='searchviewcosmetics'),
    path('addoffer', views.addoffer,name='addoffer'),
    path('addfacility_post', views.addfacility_post,name='addfacility_post'),
    path('addrental', views.addrental,name='addrental'),
    path('addrental_post', views.addrental_post,name='addrental_post'),
    path('addoffer_post', views.addoffer_post,name='addoffer_post'),
    path('addstaff', views.addstaff,name='addstaff'),
    path('addstaffattendance', views.addstaffattendance,name='addstaffattendance'),
    path('assignworkstaff/<id>', views.assignworkstaff,name='assignworkstaff'),
    path('branchhome', views.branchhome,name='branchhome'),
    path('adssigned', views.adssigned,name='adssigned'),
    path('managecosmetics', views.managecosmetics,name='managecosmetics'),
    path('managestaffattendance', views.managestaffattendance,name='managestaffattendance'),
    path('updatestock_post', views.updatestock_post,name='updatestock_post'),
    path('updatestock/<int:id>', views.updatestock,name='updatestock'),
    path('deletestff/<int:id>', views.deletestff,name='deletestff'),
    path('addstaff_post', views.addstaff_post,name='addstaff_post'),
    path('deletestock/<int:id>/<cosid>', views.deletestock,name='deletestock'),
    path('viewapprovebooking', views.viewapprovebooking,name='viewapprovebooking'),
    path('viewleavedetails', views.viewleavedetails,name='viewleavedetails'),
    path('viewmanagefacility', views.viewmanagefacility,name='viewmanagefacility'),
    path('viewmanageinventory', views.viewmanageinventory,name='viewmanageinventory'),
    path('viewmanageoffer', views.viewmanageoffer,name='viewmanageoffer'),
    path('viewmanagestaff', views.viewmanagestaff,name='viewmanagestaff'),
    path('viewrentalproducts', views.viewrentalproducts,name='viewrentalproducts'),
    path('Viewcustomers', views.Viewcustomers,name='Viewcustomers'),
    path('adminshome', views.adminshome,name='adminshome'),
    path('map1', views.map1,name='map1'),
    path('map', views.map,name='map'),
    path('mapcode', views.mapcode,name='mapcode'),
    path('admin_add_category', views.admin_add_category,name='admin_add_category'),
    path('admin_view_category', views.admin_view_category,name='admin_view_category'),
    path('salarycalculation', views.salarycalculation,name='salarycalculation'),
    path('generatebill', views.generatebill,name='generatebill'),
    path('addfacility', views.addfacility,name='addfacility'),
    path('addcosmetic_post', views.addcosmetic_post,name='addcosmetic_post'),
    path('viewstaffsalary', views.viewstaffsalary,name='viewstaffsalary'),
    path('editbranch_post', views.editbranch_post,name='editbranch_post'),
    path('addbranch_post', views.addbranch_post,name='addbranch_post'),
    path('viewstaffattendance', views.viewstaffattendance,name='viewstaffattendance'),
    path('searchbranch', views.searchbranch,name='searchbranch'),
    path('searchstaff', views.searchstaff,name='searchstaff'),
    path('editstaff_post', views.editstaff_post,name='editstaff_post'),
    path('searchcustomer', views.searchcustomer,name='searchcustomer'),
    path('deletebranch/<int:id>', views.deletebranch,name='deletebranch'),
    path('deletecosmetics/<int:id>', views.deletecosmetics,name='deletecosmetics'),
    path('deletetfacility/<int:id>', views.deletetfacility,name='deletetfacility'),
    path('deleteinventory/<int:id>', views.deleteinventory,name='deleteinventory'),
    path('deleterental/<int:id>', views.deleterental,name='deleterental'),
    path('editstaff/<int:id>', views.editstaff,name='editstaff'),
    path('deleteoffer/<int:id>', views.deleteoffer,name='deleteoffer'),
    path('editinventory/<int:id>', views.editinventory,name='editinventory'),
    path('editinventory_post', views.editinventory_post,name='editinventory_post'),
    path('editbranch/<int:id>', views.editbranch,name='editbranch'),
    path('editcosmetic/<int:id>', views.editcosmetic,name='editcosmetic'),
    path('editcosmetic_post', views.editcosmetic_post,name='editcosmetic_post'),
    path('editfacility/<int:id>', views.editfacility,name='editfacility'),
    path('editfacility_post', views.editfacility_post,name='editfacility_post'),
    path('searchviewmanageinventory', views.searchviewmanageinventory,name='searchviewmanageinventory'),
    path('viewmanageoffer_search', views.viewmanageoffer_search,name='viewmanageoffer_search'),
    path('editrental_post', views.editrental_post,name='editrental_post'),
    path('editrental/<int:id>', views.editrental,name='editrental'),
    path('deletecategory/<int:id>', views.deletecategory,name='deletecategory'),
    path('searchcategory', views.searchcategory,name='searchcategory'),
    path('and_logincode', views.and_logincode,name='and_logincode'),
    path('cosmeticsearch', views.cosmeticsearch,name='cosmeticsearch'),
    path('adssign', views.adssign,name='adssign'),
    path('reject_leave/<id>', views.reject_leave,name='reject_leave'),
    path('acceptleave/<id>', views.acceptleave,name='acceptleave'),
    path('searchleaverqst', views.searchleaverqst,name='searchleaverqst'),
    path('viewaccapprovebooking', views.viewaccapprovebooking,name='viewaccapprovebooking'),
    path('moredetailssearch', views.moredetailssearch,name='moredetailssearch'),
    path('assign_post', views.assign_post,name='assign_post'),
    path('acceptbookings/<id>', views.acceptbookings,name='acceptbookings'),
    path('moredetails/<id>', views.moredetails,name='moredetails'),
    path('moredetails_one/<id>', views.moredetails_one,name='moredetails_one'),
    path('rejectbookings/<id>', views.rejectbookings,name='rejectbookings'),
    path('logout', views.logout,name='logout'),
    path('viewstaff_post', views.viewstaff_post,name='viewstaff_post'),
    path('viewstaffsalarysearch', views.viewstaffsalarysearch,name='viewstaffsalarysearch'),
    path('acceptfacility/<id>', views.acceptfacility,name='acceptfacility'),
    path('rejecttfacility/<id>', views.rejecttfacility,name='rejecttfacility'),
    path('deleteattendance/<id>', views.deleteattendance,name='deleteattendance'),
    path('managestaffattendance_post', views.managestaffattendance_post,name='managestaffattendance_post'),


    path('insertAttendance', views.insertAttendance,name='insertAttendance'),


    #------------------------android_____________________

    path('registration', views.registration,name='registration'),
    path('and_viewbranches', views.and_viewbranches,name='and_viewbranches'),
    path('and_viewfacilities', views.and_viewfacilities,name='and_viewfacilities'),
    path('and_viewrental', views.and_viewrental,name='and_viewrental'),
    path('and_viewfacilities_search', views.and_viewfacilities_search,name='and_viewfacilities_search'),
    path('and_viewrentalsearch', views.and_viewrentalsearch,name='and_viewrentalsearch'),
    path('and_view_sloat', views.and_view_sloat,name='and_view_sloat'),
    path('add_to_cart', views.add_to_cart,name='add_to_cart'),
    path('view_cart', views.view_cart,name='view_cart'),
    path('delete_cart', views.delete_cart,name='delete_cart'),
    path('Purchase_cart', views.Purchase_cart,name='Purchase_cart'),
    path('and_staffrequestsend', views.and_staffrequestsend,name='and_staffrequestsend'),
    path('and_view_leavereqsr', views.and_view_leavereqsr,name='and_view_leavereqsr'),
    path('delete_leave', views.delete_leave,name='delete_leave'),
    path('and_viewbookings', views.and_viewbookings,name='and_viewbookings'),
    path('and_viewbooking_more', views.and_viewbooking_more,name='and_viewbooking_more'),
    path('and_view_attendance', views.and_view_attendance,name='and_view_attendance'),
    path('and_view_works', views.and_view_works,name='and_view_works'),
    path('and_update_work', views.and_update_work,name='and_update_work'),
    path('Rental_add_to_cart', views.Rental_add_to_cart,name='Rental_add_to_cart'),
    path('view_rental_cart', views.view_rental_cart,name='view_rental_cart'),
    path('delete_rental', views.delete_rental,name='delete_rental'),
    path('view_order_data', views.view_order_data,name='view_order_data'),
    path('paymentfinish', views.paymentfinish,name='paymentfinish'),
    path('sendfeedback', views.sendfeedback,name='sendfeedback'),
    path('and_view_feedback', views.and_view_feedback,name='and_view_feedback'),
    path('sendfeedbackbrnch', views.sendfeedbackbrnch,name='sendfeedbackbrnch'),
    path('view_reply', views.view_reply,name='view_reply'),
    path('send_complaints', views.send_complaints,name='send_complaints'),
    path('and_view_offer', views.and_view_offer,name='send_coand_view_offer'),
    path('viewhistory', views.viewhistory,name='viewhistory'),
    path('feedbacksearch', views.feedbacksearch,name='feedbacksearch'),


    path('and_view_attendance_and_slary', views.and_view_attendance_and_slary,name='and_view_attendance_and_slary'),
    path('and_view_rental_booking', views.and_view_rental_booking,name='and_view_rental_booking'),






]
